name: Build and Push to Docker Hub

on:
  push:
    branches:
      - solution/Amisha
      - environment/dev
      - main

jobs:
  build-and-push:
    name: Build and Push to Docker Hub
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Get Commit Hash
      id: commit_hash
      run: echo "::set-output name=hash::$(git rev-parse --short HEAD)"

    - name: Build and Push Docker Image
      run: |
        VERSION="v1.${{ github.run_number }}.${{ steps.commit_hash.outputs.hash }}"
        TAGNAME="weather-application-${VERSION}"
        docker build -t amisha2812/weather-node-local:$TAGNAME .
        docker push amisha2812/weather-node-local:$TAGNAME

        
